spring.application.name=configServer
spring.profiles.active=native
server.port=8888
spring.cloud.config.server.native.search-locations=file:///C:/Users/Administrator/Documents/ecommerce-spring-boot-micro-service/configServer/src/main/resources/config

#rabbitmq
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VIRTUAL_HOST:/}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL_ENABLED:false}

#Actuator
management.endpoints.web.exposure.include=*
